name: plan-workflow

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs: 
      environment: 'description environment selection'
      type: environment
      required: true


jobs:  
  build: 
  runs-on: ubuntu-latest
  steps:
   - run: echo ${{ github.event.name }}
  