name: plan-workflow

on:
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
    inputs: 
      environment:
        description: 'description environment selection'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'dev' || github.event.inputs.environment }}    
    steps:
    - name: 'echo environment variables'
      run: |
        echo "event name is ${{ github.event_name }}"
        echo "event name is ${{ vars.API_KEY }}"
        echo "event name is ${{ vars.APP_NAME }}"
        echo "Completing workflow..."